In [54]:
import sys
import json

from pathlib import Path
from dateutil import parser

import requests
import fiona

import pandas as pd
import geopandas as gpd

DIR = Path('..')
sys.path.append(str(DIR))

import pyotp as otp

DATA_DIR = DIR/'data/'

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Palyground

In [43]:
# setting the analysis date and time
dt = parser.parse('20/July/2017 8:00:00 AM')

in_gdf = gpd.read_file(str(DATA_DIR/'sample_locations.geojson'))

In [46]:
%time otp.route(in_gdf.head(2), 'TRANSIT,WALK','test', dt)

Wall time: 133 ms

,trip_name,leg_id,mode,from,from_name,to,to_name,route_id,trip_id,distance,duration,startTime,endTime,waitTime,geometry
0,test,0,WALK,POINT (174.8171499998194 -36.87986499959732),Origin,POINT (174.81715 -36.87986),1:7427,,,0.192,1,1500494523000,1500494524000,1000,"LINESTRING (17.481712 -3.687981, 17.481712 -3...."
1,test,1,BUS,POINT (174.81715 -36.87986),1:7427,POINT (174.76449 -36.85741),1:7149,1:62501-20170705140526_v55.10,1:14625064013-20170705140526_v55.10,6028.86,2095,1500494525000,1500496620000,1000,"LINESTRING (17.481715 -3.687986, 17.481712 -3...."
2,test,2,WALK,POINT (174.76449 -36.85741),1:7149,POINT (174.760989999634 -36.85183300038418),Destination,,,929.473,757,1500496621000,1500497378000,NaN,"LINESTRING (17.476455 -3.685747, 17.476472 -3...."

In [38]:
%time otp.service_area(in_gdf, "TRANSIT,WALK", [500, 1000], dt)

Wall time: 674 ms

                                            geometry  time
0  (POLYGON ((174.819 -36.873, 174.8174 -36.8727,...  1000
1  (POLYGON ((174.8171 -36.8768, 174.8151 -36.877...   500
0  (POLYGON ((174.761 -36.8438, 174.759 -36.8446,...  1000
1  (POLYGON ((174.761 -36.8485, 174.7599 -36.8491...   500
0  (POLYGON ((174.7374 -36.8759, 174.7374 -36.876...  1000
1  (POLYGON ((174.7374 -36.8851, 174.7369 -36.885...   500

In [39]:
od_set = gpd.read_file(str(DATA_DIR/'od_set.geojson'))
od_set['location_name'] = 'location: '+ od_set.index.astype(str)
od_set

                                       geometry route_id location_name
0  POINT (174.7298018990001 -36.87621789599996)        1   location: 0
1  POINT (174.7639865660001 -36.84994778099997)        1   location: 1
2  POINT (174.7647225510001 -36.90041207899998)        2   location: 2
3  POINT (174.7271483520001 -36.89949745399997)        2   location: 3
4  POINT (174.7085681680001 -36.88324049999994)        3   location: 4
5   POINT (174.8049270710001 -36.9133301599999)        3   location: 5
6      POINT (174.830714979 -36.89881761199996)        4   location: 6
7      POINT (174.835486799 -36.86993589899998)        4   location: 7
8  POINT (174.7980088750001 -36.88176517999995)        5   location: 8
9  POINT (174.7413818690001 -36.85628036899993)        5   location: 9

In [55]:
%time otp.od_matrix_unlimited(od_set, od_set, 'multimodal', 'location_name', 'location_name', dt)

Analysis started at: 2017-08-09 14:15:25.896196
Total routes caclulated: 50, time: 0:00:05.886183
Total routes caclulated: 100, time: 0:00:11.959490
Wall time: 12 s

,trip_name,leg_id,mode,from,from_name,to,to_name,route_id,trip_id,distance,duration,startTime,endTime,waitTime,geometry
0,from location: 0 to location: 1,0,WALK,POINT (174.7298018990001 -36.87621789599996),Origin,POINT (174.73232 -36.8756),1:8219,,,283.621,224,1500494785000,1500495009000,1000,"LINESTRING (17.47298 -3.687612, 17.472991 -3.6..."
1,from location: 0 to location: 1,1,BUS,POINT (174.73232 -36.8756),1:8219,POINT (174.76373 -36.85073),1:7086,1:22107-20170705140526_v55.10,1:18157083760-20170705140526_v55.10,4607.71,1294,1500495010000,1500496304000,1000,"LINESTRING (17.473232 -3.68756, 17.473236 -3.6..."
2,from location: 0 to location: 1,2,WALK,POINT (174.76373 -36.85073),1:7086,POINT (174.7639865660001 -36.84994778099997),Destination,,,106.37,90,1500496305000,1500496395000,NaN,"LINESTRING (17.476375 -3.685068, 17.476357 -3...."
3,from location: 0 to location: 2,0,WALK,POINT (174.7298018990001 -36.87621789599996),Origin,POINT (174.73521 -36.87499),1:0104,,,566.369,459,1500494720000,1500495179000,1000,"LINESTRING (17.47298 -3.687612, 17.472991 -3.6..."
4,from location: 0 to location: 2,1,RAIL,POINT (174.73521 -36.87499),1:0104,POINT (174.75899 -36.86796),1:0118,1:10235-20170705140526_v55.10,1:17000070515-20170705140526_v55.10,2255.91,300,1500495180000,1500495480000,0,"LINESTRING (17.473521 -3.687499, 17.473631 -3...."
5,from location: 0 to location: 2,2,WALK,POINT (174.75899 -36.86796),1:0118,POINT (174.76093 -36.86837),1:8502,,,185.988,142,1500495480000,1500495622000,99000,"LINESTRING (17.475899 -3.686795, 17.4759 -3.68..."
6,from location: 0 to location: 2,3,BUS,POINT (174.76093 -36.86837),1:8502,POINT (174.75738 -36.89814),1:8524,1:27402-20170705140526_v55.10,1:14274069470-20170705140526_v55.10,3373.46,915,1500495721000,1500496636000,1000,"LINESTRING (17.476093 -3.686837, 17.476087 -3...."
7,from location: 0 to location: 2,4,WALK,POINT (174.75738 -36.89814),1:8524,POINT (174.7647225510001 -36.90041207899998),Destination,,,972.371,754,1500496637000,1500497391000,NaN,"LINESTRING (17.475734 -3.689814, 17.475726 -3...."
8,from location: 0 to location: 3,0,WALK,POINT (174.7298018990001 -36.87621789599996),Origin,POINT (174.73521 -36.87499),1:0104,,,566.369,459,1500494480000,1500494939000,1000,"LINESTRING (17.47298 -3.687612, 17.472991 -3.6..."
9,from location: 0 to location: 3,1,RAIL,POINT (174.73521 -36.87499),1:0104,POINT (174.71409 -36.88478),1:0120,1:10234-20170705140526_v55.10,1:17000070414-20170705140526_v55.10,2317.75,300,1500494940000,1500495240000,0,"LINESTRING (17.473525 -3.687506, 17.47342 -3.6..."
10,from location: 0 to location: 3,2,WALK,POINT (174.71409 -36.88478),1:0120,POINT (174.71663 -36.88473),1:8812,,,361.811,275,1500495240000,1500495515000,279000,"LINESTRING (17.471411 -3.68848, 17.471478 -3.6..."
11,from location: 0 to location: 3,3,BUS,POINT (174.71663 -36.88473),1:8812,POINT (174.72617 -36.89329),1:8820,1:00702-20170705140526_v55.10,1:14007063822-20170705140526_v55.10,1296.29,126,1500495794000,1500495920000,1000,"LINESTRING (17.471663 -3.688473, 17.471658 -3...."
12,from location: 0 to location: 3,4,WALK,POINT (174.72617 -36.89329),1:8820,POINT (174.7271483520001 -36.89949745399997),Destination,,,931.16,734,1500495921000,1500496655000,NaN,"LINESTRING (17.472613 -3.689334, 17.472666 -3...."
13,from location: 0 to location: 4,0,WALK,POINT (174.7298018990001 -36.87621789599996),Origin,POINT (174.72855 -36.8792),1:8868,,,781.993,612,1500495058000,1500495670000,1000,"LINESTRING (17.47298 -3.687612, 17.47276 -3.68..."
14,from location: 0 to location: 4,1,BUS,POINT (174.72855 -36.8792),1:8868,POINT (174.71115 -36.87951),1:8033,1:73102-20170705140526_v55.10,1:14731045593-20170705140526_v55.10,1840.25,426,1500495671000,1500496097000,1000,"LINESTRING (17.472855 -3.68792, 17.472861 -3.6..."
15,from location: 0 to location: 4,2,WALK,POINT (174.71115 -36.87951),1:8033,POINT (174.7085681680001 -36.88324049999994),Destination,,,587.696,468,1500496098000,1500496566000,NaN,"LINESTRING (17.471119 -3.68795, 17.471132 -3.6..."
16,from location: 0 to location: 5,0,WALK,POINT (174.7298018990001 -36.87621789599996),Origin,POINT (174.73521 -36.87499),1:0104,,,566.369,459,1500494720000,1500495179000,1000,"LINESTRING (17.47298 -3.687612, 17.472991 -3.6..."
17,from location: 0 to location: 5,1,RAIL,POINT (174.73521 -36.87499),1:0104,POINT (174.76984 -36.86561),1:0277,1:10235-20170705140526_v55.10,1:17000070515-20170705140526_v55.10,3255.87,420,1500495180000,1500495600000,0,"LINESTRING (17.473521 -3.687499, 17.473631 -3...."
18,from location: 0 to location: 5,2,WALK,POINT (174.76984 -36.86561),1:0277,POINT (174.77139 -36.86617),1:7176,,,257.931,196,1500495600000,1500495796000,4000,"LINESTRING (17.476984 -3.686562, 17.47697 -3.6..."
19,from location: 0 to location: 5,3,BUS,POINT (174.77139 -36.86617),1:7176,POINT (174.8009 -36.91309),1:8387,1:31202-20170705140526_v55.10,1:14312054660-20170705140526_v55.10,9005.75,1968,1500495800000,1500497768000,1000,"LINESTRING (17.477139 -3.686617, 17.477137 -3...."
20,from location: 0 to location: 5,4,WALK,POINT (174.8009 -36.91309),1:8387,POINT (174.8049270710001 -36.9133301599999),Destination,,,468.321,377,1500497769000,1500498146000,NaN,"LINESTRING (17.480084 -3.69131, 17.480084 -3.6..."
21,from location: 0 to location: 6,0,WALK,POINT (174.7298018990001 -36.87621789599996),Origin,POINT (174.73521 -36.87499),1:0104,,,566.369,459,1500494720000,1500495179000,1000,"LINESTRING (17.47298 -3.687612, 17.472991 -3.6..."
22,from location: 0 to location: 6,1,RAIL,POINT (174.73521 -36.87499),1:0104,POINT (174.77883 -36.86972),1:0115,1:10235-20170705140526_v55.10,1:17000070515-20170705140526_v55.10,4176.98,660,1500495180000,1500495840000,60000,"LINESTRING (17.473521 -3.687499, 17.473631 -3...."
23,from location: 0 to location: 6,2,RAIL,POINT (174.77883 -36.86972),1:0115,POINT (174.80811 -36.89847),1:0112,1:20326-20170705140526_v55.10,1:23100075715-20170705140526_v55.10,4197.45,480,1500495900000,1500496380000,0,"LINESTRING (17.477884 -3.686973, 17.477884 -3...."
24,from location: 0 to location: 6,3,WALK,POINT (174.80811 -36.89847),1:0112,POINT (174.80569 -36.89659),1:7502,,,352.5,268,1500496380000,1500496648000,50000,"LINESTRING (17.48082 -3.689844, 17.480808 -3.6..."
25,from location: 0 to location: 6,4,BUS,POINT (174.80569 -36.89659),1:7502,POINT (174.83229 -36.89674),1:7518,1:50002-20170705140526_v55.10,1:5500072933-20170705140526_v55.10,2469.54,365,1500496698000,1500497063000,1000,"LINESTRING (17.480569 -3.68966, 17.480568 -3.6..."
26,from location: 0 to location: 6,5,WALK,POINT (174.83229 -36.89674),1:7518,POINT (174.830714979 -36.89881761199996),Destination,,,445.416,346,1500497064000,1500497410000,NaN,"LINESTRING (17.483229 -3.68968, 17.483193 -3.6..."
27,from location: 0 to location: 7,0,WALK,POINT (174.7298018990001 -36.87621789599996),Origin,POINT (174.73232 -36.8756),1:8219,,,283.621,224,1500494785000,1500495009000,1000,"LINESTRING (17.47298 -3.687612, 17.472991 -3.6..."
28,from location: 0 to location: 7,1,BUS,POINT (174.73232 -36.8756),1:8219,POINT (174.76449 -36.85741),1:7149,1:22107-20170705140526_v55.10,1:18157083760-20170705140526_v55.10,3587.6,910,1500495010000,1500495920000,0,"LINESTRING (17.473232 -3.68756, 17.473236 -3.6..."
29,from location: 0 to location: 7,2,WALK,POINT (174.76449 -36.85741),1:7149,POINT (174.76452 -36.85759),1:7159,,,12.448,12,1500495920000,1500495932000,88000,"LINESTRING (17.476455 -3.685747, 17.476449 -3...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367,from location: 9 to location: 1,1,BUS,POINT (174.74053 -36.85694),1:8077,POINT (174.7649 -36.8499),1:7053,1:02001-20170705140526_v55.10,1:14020064972-20170705140526_v55.10,3658.83,1329,1500495059000,1500496388000,1000,"LINESTRING (17.474053 -3.685694, 17.474048 -3...."
368,from location: 9 to location: 1,2,WALK,POINT (174.7649 -36.8499),1:7053,POINT (174.7639865660001 -36.84994778099997),Destination,,,111.996,95,1500496389000,1500496484000,NaN,"LINESTRING (17.476488 -3.684993, 17.476493 -3...."
369,from location: 9 to location: 2,0,WALK,POINT (174.7413818690001 -36.85628036899993),Origin,POINT (174.74717 -36.85659),1:7215,,,570.768,442,1500494656000,1500495098000,1000,"LINESTRING (17.474139 -3.685641, 17.474202 -3...."
370,from location: 9 to location: 2,1,BUS,POINT (174.74717 -36.85659),1:7215,POINT (174.76394 -36.90947),1:8844,1:01002-20170705140526_v55.10,1:14010064662-20170705140526_v55.10,11123.5,1818,1500495099000,1500496917000,0,"LINESTRING (17.474717 -3.685659, 17.474712 -3...."
371,from location: 9 to location: 2,2,WALK,POINT (174.76394 -36.90947),1:8844,POINT (174.76361 -36.90893),1:8649,,,93.42,73,1500496917000,1500496990000,112000,"LINESTRING (17.476392 -3.690951, 17.476355 -3...."
372,from location: 9 to location: 2,3,BUS,POINT (174.76361 -36.90893),1:8649,POINT (174.7677 -36.90084),1:8641,1:29901-20170705140526_v55.10,1:14299069544-20170705140526_v55.10,982.992,125,1500497102000,1500497227000,1000,"LINESTRING (17.476361 -3.690893, 17.476365 -3...."
373,from location: 9 to location: 2,4,WALK,POINT (174.7677 -36.90084),1:8641,POINT (174.7647225510001 -36.90041207899998),Destination,,,452.852,351,1500497228000,1500497579000,NaN,"LINESTRING (17.476773 -3.690085, 17.476765 -3...."
374,from location: 9 to location: 3,0,WALK,POINT (174.7413818690001 -36.85628036899993),Origin,POINT (174.74717 -36.85659),1:7215,,,570.768,442,1500494656000,1500495098000,1000,"LINESTRING (17.474139 -3.685641, 17.474202 -3...."
375,from location: 9 to location: 3,1,BUS,POINT (174.74717 -36.85659),1:7215,POINT (174.72975 -36.89506),1:8822,1:01002-20170705140526_v55.10,1:14010064662-20170705140526_v55.10,7494.38,1277,1500495099000,1500496376000,1000,"LINESTRING (17.474717 -3.685659, 17.474712 -3...."
376,from location: 9 to location: 3,2,WALK,POINT (174.72975 -36.89506),1:8822,POINT (174.7271483520001 -36.89949745399997),Destination,,,679.884,532,1500496377000,1500496909000,NaN,"LINESTRING (17.472972 -3.68951, 17.472959 -3.6..."
377,from location: 9 to location: 4,0,WALK,POINT (174.7413818690001 -36.85628036899993),Origin,POINT (174.74717 -36.85659),1:7215,,,570.768,442,1500494656000,1500495098000,1000,"LINESTRING (17.474139 -3.685641, 17.474202 -3...."
378,from location: 9 to location: 4,1,BUS,POINT (174.74717 -36.85659),1:7215,POINT (174.71119 -36.87926),1:8032,1:01002-20170705140526_v55.10,1:14010064662-20170705140526_v55.10,5031.03,822,1500495099000,1500495921000,1000,"LINESTRING (17.474717 -3.685659, 17.474712 -3...."
379,from location: 9 to location: 4,2,WALK,POINT (174.71119 -36.87926),1:8032,POINT (174.7085681680001 -36.88324049999994),Destination,,,614.034,490,1500495922000,1500496412000,NaN,"LINESTRING (17.471113 -3.687927, 17.471118 -3...."
380,from location: 9 to location: 5,0,WALK,POINT (174.7413818690001 -36.85628036899993),Origin,POINT (174.74717 -36.85659),1:7215,,,570.768,442,1500494973000,1500495415000,1000,"LINESTRING (17.474139 -3.685641, 17.474202 -3...."
381,from location: 9 to location: 5,1,BUS,POINT (174.74717 -36.85659),1:7215,POINT (174.77725 -36.86741),1:7180,1:79801-20170705140526_v55.10,1:14798066072-20170705140526_v55.10,3354.67,983,1500495416000,1500496399000,0,"LINESTRING (17.474717 -3.685659, 17.474712 -3...."
382,from location: 9 to location: 5,2,WALK,POINT (174.77725 -36.86741),1:7180,POINT (174.77883 -36.86972),1:0115,,,439.992,333,1500496399000,1500496732000,608000,"LINESTRING (17.477723 -3.686747, 17.47773 -3.6..."
383,from location: 9 to location: 5,3,RAIL,POINT (174.77883 -36.86972),1:0115,POINT (174.80137 -36.92013),1:0606,1:40056-20170705140526_v55.10,1:51100070793-20170705140526_v55.10,7274.93,720,1500497340000,1500498060000,1000,"LINESTRING (17.477884 -3.686973, 17.47787 -3.6..."
384,from location: 9 to location: 5,4,WALK,POINT (174.80137 -36.92013),1:0606,POINT (174.8049270710001 -36.9133301599999),Destination,,,982.303,779,1500498061000,1500498840000,NaN,"LINESTRING (17.480138 -3.692015, 17.48018 -3.6..."
385,from location: 9 to location: 6,0,WALK,POINT (174.7413818690001 -36.85628036899993),Origin,POINT (174.74717 -36.85659),1:7215,,,570.768,442,1500494973000,1500495415000,1000,"LINESTRING (17.474139 -3.685641, 17.474202 -3...."
386,from location: 9 to location: 6,1,BUS,POINT (174.74717 -36.85659),1:7215,POINT (174.77714 -36.87304),1:7208,1:79801-20170705140526_v55.10,1:14798066072-20170705140526_v55.10,3980.78,1091,1500495416000,1500496507000,437000,"LINESTRING (17.474717 -3.685659, 17.474712 -3...."
387,from location: 9 to location: 6,2,BUS,POINT (174.77714 -36.87304),1:7208,POINT (174.83229 -36.89674),1:7518,1:50004-20170705140526_v55.10,1:5500073031-20170705140526_v55.10,6217.94,962,1500496944000,1500497906000,1000,"LINESTRING (17.477714 -3.687305, 17.477705 -3...."
388,from location: 9 to location: 6,3,WALK,POINT (174.83229 -36.89674),1:7518,POINT (174.830714979 -36.89881761199996),Destination,,,445.416,346,1500497907000,1500498253000,NaN,"LINESTRING (17.483229 -3.68968, 17.483193 -3.6..."
389,from location: 9 to location: 7,0,WALK,POINT (174.7413818690001 -36.85628036899993),Origin,POINT (174.74717 -36.85659),1:7215,,,570.768,442,1500494973000,1500495415000,1000,"LINESTRING (17.474139 -3.685641, 17.474202 -3...."
390,from location: 9 to location: 7,1,BUS,POINT (174.74717 -36.85659),1:7215,POINT (174.77074 -36.86557),1:7230,1:79801-20170705140526_v55.10,1:14798066072-20170705140526_v55.10,2738.53,814,1500495416000,1500496230000,18000,"LINESTRING (17.474717 -3.685659, 17.474712 -3...."
391,from location: 9 to location: 7,2,BUS,POINT (174.77074 -36.86557),1:7230,POINT (174.83143 -36.87299),1:7434,1:62502-20170705140526_v55.10,1:14625040135-20170705140526_v55.10,6427.22,1152,1500496248000,1500497400000,1000,"LINESTRING (17.477074 -3.686557, 17.477066 -3...."
392,from location: 9 to location: 7,3,WALK,POINT (174.83143 -36.87299),1:7434,POINT (174.835486799 -36.86993589899998),Destination,,,616.295,476,1500497401000,1500497877000,NaN,"LINESTRING (17.483143 -3.6873, 17.483216 -3.68..."
393,from location: 9 to location: 8,0,WALK,POINT (174.7413818690001 -36.85628036899993),Origin,POINT (174.74717 -36.85659),1:7215,,,570.768,442,1500494973000,1500495415000,1000,"LINESTRING (17.474139 -3.685641, 17.474202 -3...."
394,from location: 9 to location: 8,1,BUS,POINT (174.74717 -36.85659),1:7215,POINT (174.77074 -36.86557),1:7230,1:79801-20170705140526_v55.10,1:14798066072-20170705140526_v55.10,2738.53,814,1500495416000,1500496230000,18000,"LINESTRING (17.474717 -3.685659, 17.474712 -3...."
395,from location: 9 to location: 8,2,BUS,POINT (174.77074 -36.86557),1:7230,POINT (174.79654 -36.88053),1:8538,1:62502-20170705140526_v55.10,1:14625040135-20170705140526_v55.10,2992.07,549,1500496248000,1500496797000,1000,"LINESTRING (17.477074 -3.686557, 17.477066 -3...."
396,from location: 9 to location: 8,3,WALK,POINT (174.79654 -36.88053),1:8538,POINT (174.7980088750001 -36.88176517999995),Destination,,,199.981,156,1500496798000,1500496954000,NaN,"LINESTRING (17.479653 -3.688059, 17.479726 -3...."